# Generated by Django 3.0.6 on 2020-09-11 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('search_date', models.CharField(default='11.9.2020', max_length=30, verbose_name='Ngày tìm kiếm')),
                ('name', models.CharField(max_length=60, null=True, unique=True, verbose_name='Khách hàng')),
                ('popular_info', models.TextField(default='', max_length=1000, verbose_name='Thông tin chung')),
                ('private_info', models.TextField(default='', max_length=1000, verbose_name='Thông tin riêng')),
                ('customer_type', models.CharField(choices=[('Khách lẻ', 'Khách lẻ'), ('Khách tháng', 'Khách tháng'), ('IDT mới', 'IDT mới'), ('IDT cũ', 'IDT cũ'), ('Khác', 'Khác')], default='Khách lẻ', max_length=200, null=True, verbose_name='Loại KH')),
                ('city', models.CharField(choices=[('Miền Bắc', 'Miền Bắc'), ('Miền Nam', 'Miền Nam'), ('Miền Trung', 'Miền Trung'), ('Khác', 'Khác')], default='Miền Nam', max_length=200, null=True, verbose_name='Thành phố')),
                ('status', models.BooleanField(default=False, verbose_name='Tình Trạng làm việc')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('search_date', models.CharField(default='11.9.2020', max_length=30, verbose_name='Ngày tìm kiếm')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('name', models.CharField(default='Phiếu thu ', max_length=60, null=True, verbose_name='Tên phiếu thu')),
                ('deposit', models.IntegerField(default=0, verbose_name='Đã thu')),
                ('popular_info', models.TextField(default='- Tổng tiền chốt khách: \n- Deadline: ', max_length=1000, null=True, verbose_name='Lưu ý')),
                ('status', models.BooleanField(default=False, verbose_name='Xác nhận thực hiện')),
                ('payment_status', models.BooleanField(default=False, verbose_name='Tình Trạng thanh toán')),
                ('send_status', models.BooleanField(default=False, verbose_name='Trả đơn')),
                ('approved_status', models.BooleanField(default=False, verbose_name='Duyệt thu')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='khachhang.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('search_date', models.CharField(default='11.9.2020', max_length=30, verbose_name='Ngày tìm kiếm')),
                ('order_type', models.CharField(choices=[('Dịch thuật', 'Dịch thuật'), ('Dịch video', 'Dịch video'), ('Công chứng', 'Công chứng'), ('Sao y', 'Sao y'), ('HPHLS', 'HPHLS'), ('Ship', 'Ship'), ('VAT', 'VAT'), ('Khác', 'Khác')], default='Dịch thuật', max_length=200, null=True, verbose_name='Loại Đơn hàng')),
                ('language_type', models.CharField(blank=True, choices=[('Tiếng Anh', 'Tiếng Anh'), ('Tiếng Trung', 'Tiếng Trung'), ('Tiếng Nhật', 'Tiếng Nhật'), ('Tiếng Hàn', 'Tiếng Hàn'), ('Tiếng Pháp', 'Tiếng Pháp'), ('Tiếng Đức', 'Tiếng Đức'), ('Tiếng Nga', 'Tiếng Nga')], max_length=200, verbose_name='Loại Ngôn ngữ')),
                ('name', models.CharField(blank=True, max_length=60, verbose_name='Tên tài liệu/ Dịch vụ')),
                ('quantity', models.IntegerField(default=0, verbose_name='Số lượng')),
                ('unit', models.CharField(choices=[('Trang', 'Trang'), ('Bộ', 'Bộ'), ('Lần', 'Lần'), ('Phút', 'Phút')], max_length=20, null=True, verbose_name='Đơn vị')),
                ('price', models.IntegerField(default=0, verbose_name='Đơn giá')),
                ('popular_info', models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Lưu ý')),
                ('receipt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='khachhang.Receipt')),
            ],
        ),
    ]
